#!/usr/bin/env sh
# Dependencies: coreutils, lame, faac and findutils

usage() {
  local prg="$1"
  echo "A tool to convert mp3 files to one m4b file."
  echo "Takes a list of mp3 files to convert on stdin (absolute paths)."
  echo ""
  echo "Usage: cat <mp3 list> | $prg [options]"
  echo ""
  echo "Help options:"
  echo "    -h    Short help on using $prg"
  echo ""
  echo "Program options:"
  echo "    -a    Author"
  echo "    -b    Book title"
  echo "    -o    Output directory"
  echo ""
  echo "Example:"
  echo "    ls ~/book/**.mp3 | sort -n | $prg -a \"John Doe\" -b \"Seeds\""
}

check_env() {
  local nbr=$(for prg in $@
    do
      command -v $prg || echo "Command $prg not found." 1>&2
    done | wc -l)
  return $(($# - $nbr))
}

AUTHOR="Unkown author"
BOOK="Unkown title"
OUTDIR="$(pwd)"
OUTPUT="/dev/null"
while getopts "a:b:o:hv" option
do
  case "$option" in
    a)
      AUTHOR=$OPTARG
      ;;
    b)
      BOOK=$OPTARG
      ;;
    o)
      OUTDIR=$OPTARG
      ;;
    v)
      OUTPUT="/dev/tty"
      ;;
    h)
      usage "$(basename "$0")"
      exit 1;
      ;;
  esac
done

check_env xargs lame faac || exit 1

if [ ! -d "$OUTDIR" ]
then
  echo "Output directory does not exist." 1>&2
  exit 1
fi

xargs -I % -n 1 lame  -h --mp3input --decode % - 2>$OUTPUT | \
  faac --artist "$AUTHOR" --album "$BOOK" \
  --ignorelength -w -q 80 -o "$OUTDIR/$AUTHOR-$BOOK.m4b" - 2>$OUTPUT

if [ $? -ne 0 ]
then
 echo "Command exited with error, run with -v for more info" 1>&2
 exit 1
fi
